name: Donwload and scan image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        required: true
        description: Digite a url/tag da imagem docker
        type: string

jobs: 
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.TST.DOCKERHUB_USERNAME }}
          password: ${{ secrets.TST.DOCKERHUB_TOKEN }}

      - name: Mostra a url/tag da image passada
        run: echo A tag passada eh ${{ inputs.image_tag }}

      - name: Baixando imagem
        run: docker pull ${{ inputs.image_tag }}

      - name: listando a imagem
        run: docker images      

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare
          image: ${{ inputs.image_tag }}
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true        