name: Validacao Imagem Docker Security

on:
  workflow_dispatch:
    inputs:
      validaImagemDocker:
        description: 'Validação da imagem escolhida pelo usuário'
        required: false
        default: 'nginx:latest'
        type: string

# Scan image security ###Teste
jobs:
  pipeline-seguranca:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Baixa a imagem do container
        run: |
          docker pull ${{ github.event.inputs.validaImagemDocker }}

      - name: Listando a imagem já baixada no step anterior 
        run: |
          IMAGE_NAME=$(echo "${{ github.event.inputs.validaImagemDocker }}" | cut -d ':' -f 1)
          docker images | grep $IMAGE_NAME

      - name: Scan com o Docker Scout
        uses: docker/scout-action@v1
        with:
          command: quickview,cves,recommendations
          image: ${{ github.event.inputs.validaImagemDocker }}
          only-severities: critical,high